# 2D Numpy in Python

##### Problem 1: Consider the following list a, convert it to Numpy Array.:

In [2]:
import numpy as np

# Write your code below 
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
a = np.array(a)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##### Problem 2: Calculate the numpy array size.


In [4]:
a.size

12

##### Problem 3: Access the element on the first row and first and second columns.

In [13]:
a[0,:2]
#or a[0][0:2]


array([1, 2])

##### Problem 4: Perform matrix multiplication with the numpy arrays A and B.

In [17]:
# Write your code below

b = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
mult = np.dot(a,b)
mult

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])